name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Assuming your main code lives in 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Use the Node version that matches your development environment

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: dist  # This should now point to 'dist' instead of 'build'
        token: ${{ secrets.GITHUB_TOKEN }}
